version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/spectral-ruleset-govuk-public"
    schedule:
      interval: "daily"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
