name: Build + test `spectral-ruleset-govuk-public`

on:
  push:
    paths:
      - "spectral-ruleset-govuk-public/**"
      - ".github/workflows/spectral-ruleset-govuk-public-ci.yml"
  pull_request:
    paths:
      - "spectral-ruleset-govuk-public/**"
      - ".github/workflows/spectral-ruleset-govuk-public-ci.yml"

permissions:
  contents: read

jobs:
  build:
    defaults:
      run:
        working-directory: spectral-ruleset-govuk-public
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@8f4b7f84864484a7bf31766abe9204da3cbe65b3
    - name: Use Node.js 16.x
      uses: actions/setup-node@64ed1c7eab4cce3362f8c340dee64e5eaeef8f7c
      with:
        node-version: '16.x'
        cache: 'npm'
        cache-dependency-path: spectral-ruleset-govuk-public/package-lock.json
    - run: npm ci
    - run: npm run lint
    - run: npm test

  publish:
    environment: npm
    if: github.ref == 'refs/heads/main'
    needs: build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@8f4b7f84864484a7bf31766abe9204da3cbe65b3
    - name: Use Node.js 16.x
      uses: actions/setup-node@64ed1c7eab4cce3362f8c340dee64e5eaeef8f7c
      with:
        node-version: '16.x'
        cache: 'npm'
        cache-dependency-path: spectral-ruleset-govuk-public/package-lock.json
    - uses: JS-DevTools/npm-publish@0f451a94170d1699fd50710966d48fb26194d939
      with:
        package: spectral-ruleset-govuk-public/package.json
        access: public
        token: ${{ secrets.NPM_TOKEN }}
