name: Build + test `spectral-ruleset-govuk-public`

on:
  push:
    paths:
      - "spectral-ruleset-govuk-public/**"
      - ".github/workflows/spectral-ruleset-govuk-public-ci.yml"
  pull_request:
    paths:
      - "spectral-ruleset-govuk-public/**"
      - ".github/workflows/spectral-ruleset-govuk-public-ci.yml"

permissions:
  contents: read

jobs:
  build:
    defaults:
      run:
        working-directory: spectral-ruleset-govuk-public
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9
    - name: Use Node.js 16.x
      uses: actions/setup-node@5e21ff4d9bc1a8cf6de233a3057d20ec6b3fb69d
      with:
        node-version: '16.x'
        cache: 'npm'
        cache-dependency-path: spectral-ruleset-govuk-public/package-lock.json
    - run: npm ci
    - run: npm run lint
    - run: npm test

  publish:
    environment: npm
    if: github.ref == 'refs/heads/main'
    needs: build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9
    - name: Use Node.js 16.x
      uses: actions/setup-node@5e21ff4d9bc1a8cf6de233a3057d20ec6b3fb69d
      with:
        node-version: '16.x'
        cache: 'npm'
        cache-dependency-path: spectral-ruleset-govuk-public/package-lock.json
    - uses: JS-DevTools/npm-publish@a25b4180b728b0279fca97d4e5bccf391685aead
      with:
        package: spectral-ruleset-govuk-public/package.json
        access: public
        token: ${{ secrets.NPM_TOKEN }}
